name: pro_lints
description: Common Lints package.

repository: https://github.com/pro100andrey/pro_lints
issue_tracker: https://github.com/pro100andrey/pro_lints/issues
homepage: https://github.com/pro100andrey/pro_lints
documentation: https://github.com/pro100andrey/pro_lints/blob/main/README.md

version: 2.0.4

environment:
  sdk: ^3.4.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - lints
